ERP_Harapan/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.login_view, name='login'),
    path('login_verify/', views.login_verify, name='login_verify'),
    path('index/', views.index, name='index'),
    path('dashboard/', views.get_dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    path('end_session/', views.end_session, name='end_session'),

    path('inventory/', include("Inventory.urls")),
    path('purcashing/', include("Purchasing.urls")),
    path('sales/', include("Sales.urls")),
    path('management/', include("Management.urls")),
]

Inventory/urls.py
from django.urls import include, path
from django.shortcuts import render, redirect
from . import views

app_name = "Inventory"

urlpatterns = [
    path("", views.get_inventory, name="index"),
    path("modify_item/", views.modify_item, name="modify_item"),
    path("post_item/", views.post_item, name="post_item"),
    path("get_stack/", views.get_stack, name="get_stack"),
    path("get_item_list/", views.get_item_list, name="get_item_list"),
    path("get_item_stock/", views.get_item_stock, name="get_item_stock"),
    path("stock_gudang/", views.stock_gudang, name="stock_gudang"),
    path("modify_stack/", views.modify_stack, name="modify_stack"),
    path("post_stack/", views.post_stack, name="post_stack"),
    path("lunaskan/", views.lunaskan, name="lunaskan"),
    path("selesaikan/", views.selesaikan, name="selesaikan"),
    path("kembali_ke_draft/", views.kembali_ke_draft, name="kembali_ke_draft"),
    path("create_recap/", views.create_recap, name="create_recap"),
    path("get_recap/", views.get_recap, name="get_recap"),
    path("get_payment_dialog/", views.get_payment_dialog, name="get_payment_dialog"),
]

Sales/urls.py
from django.urls import include, path
from django.shortcuts import render, redirect
from . import views

app_name = "Sales"

urlpatterns = [
    path("", views.transaction_records, name="index"),
    path("mofidy_transaksi/", views.mofidy_transaksi, name="mofidy_transaksi"),
    path("post_transaksi/", views.post_transaksi, name="post_transaksi"),
    path("get_transaksi/", views.get_transaksi, name="get_transaksi"),
    path("get_barang_keluar/", views.get_barang_keluar, name="get_barang_keluar"),
    path("create_bill/", views.create_bill, name="create_bill"),
    path("get_bill/", views.get_bill, name="get_bill"),
    path("riwayat_barang_keluar/", views.riwayat_barang_keluar, name="riwayat_barang_keluar"),
    path("keluarkan_barang/", views.keluarkan_barang, name="keluarkan_barang"),
    path("post_barang_keluar/", views.post_barang_keluar, name="post_barang_keluar"),
    path("get_print_dialog/", views.get_print_dialog, name="get_print_dialog"),
    path("post_print_req/", views.post_print_req, name="post_print_req"),
]

Inventory/models.py
from django.db import models
from django.contrib.auth.models import User
from crum import get_current_user
from django.utils import timezone

class gudang (models.Model):
    nama = models.CharField(max_length=16)
    keterangan = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.nama


class item (models.Model):
    nama = models.CharField(max_length=32)
    harga = models.PositiveIntegerField()
    modal = models.PositiveIntegerField()
    ongkos = models.PositiveIntegerField()
    satuan = models.CharField(max_length=12)
    archived = models.BooleanField(default=True)
    keterangan = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.nama} ({self.satuan})"


class stack (models.Model):
    item = models.ForeignKey(item, on_delete=models.CASCADE, related_name="barang_dalam_stack")
    gudang = models.ForeignKey(gudang, on_delete=models.CASCADE, related_name="barang_dalam_gudang")

    jumlah = models.PositiveIntegerField(default=0)
    expired = models.DateField(default=None, null=True, blank=True)
    keterangan = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.item.nama} - {self.gudang} QTY: {self.jumlah:,}"


class keluar_gudang (models.Model):
    transaksi = models.ForeignKey('Sales.transaksi', on_delete=models.CASCADE, related_name="record_keluar"
                                  , null=True, blank=True)
    admin = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=get_current_user)

    tanggal = models.DateField(default=timezone.localdate)
    waktu = models.TimeField(default=timezone.localtime)

    def __str__(self):
        myDict = {}
        for index, entry in enumerate(keluar_gudang.objects.filter(transaksi=self.transaksi)):
            myDict[entry] = index
        return f"{self.transaksi}/{myDict[self] + 1:,}"


class item_keluar (models.Model):
    parent = models.ForeignKey(keluar_gudang, on_delete=models.CASCADE, related_name="item_dalam_record_keluar")
    gudang = models.ForeignKey(gudang, on_delete=models.DO_NOTHING, null=True)
    stack = models.ForeignKey(stack, on_delete=models.SET_NULL, null=True, blank=True)
    item = models.ForeignKey('Sales.item_transaksi', on_delete=models.DO_NOTHING, null=True)
    item_parent = models.ForeignKey('Inventory.item', on_delete=models.CASCADE, related_name="item_keluar")

    jumlah = models.PositiveIntegerField()
    jumlah_awal = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.parent}/{self.item} - {self.gudang} QTY: {self.jumlah_awal:,} -> {self.jumlah_awal - self.jumlah:,}"


class masuk_gudang (models.Model):
    pengiriman = models.ForeignKey('Purchasing.pengiriman', on_delete=models.CASCADE, related_name="record_masuk"
                                   , null=True, blank=True)
    admin = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=get_current_user)

    tanggal = models.DateField(default=timezone.localdate)
    waktu = models.TimeField(default=timezone.localtime)

    def __str__(self):
        myDict = {}
        for index, entry in enumerate(masuk_gudang.objects.filter(pengiriman=self.pengiriman)):
            myDict[entry] = index
        return f"{self.pengiriman}/{myDict[self] + 1:,}"


class item_masuk (models.Model):
    parent = models.ForeignKey(masuk_gudang, on_delete=models.CASCADE, related_name="item_dalam_record_masuk")
    gudang = models.ForeignKey(gudang, on_delete=models.SET_NULL, null=True)
    item = models.ForeignKey('Purchasing.item_pengiriman', on_delete=models.DO_NOTHING, null=True, related_name='item_diterima')
    item_parent = models.ForeignKey('Inventory.item', on_delete=models.CASCADE, related_name="item_masuk")

    jumlah = models.PositiveIntegerField()
    jumlah_awal = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.parent}/{self.item} - {self.gudang} QTY: {self.jumlah_awal:,} -> {self.jumlah_awal + self.jumlah:,}"

Inventory/views.py
from Sales.views import map_status
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from django.utils.formats import date_format, number_format
from django.utils.timezone import localdate
import datetime

from django.db.models import Sum, Min, Q, F
from django.db.models.functions import Coalesce

from .models import item, stack, gudang, item_keluar, item_masuk, masuk_gudang, keluar_gudang
from Sales.models import transaksi, item_transaksi
from Purchasing.models import purchase_order
from Management.models import session


@login_required
def get_inventory(request):
    query = item.objects.filter(archived=False).order_by("nama")
    jumlah_item = []
    volume_jual = []
    expired = []
    inbound = []

    for i in query:
        my_total = i.barang_dalam_stack.all().aggregate(Sum('jumlah'))['jumlah__sum']
        my_total = int(0 if my_total is None else my_total)
        jumlah_item.append(my_total)

        volume = i.barang_terjual.filter(
            transaksi__tanggal__gt=localdate() - datetime.timedelta(days=60)).aggregate(Sum('jumlah'))[
            'jumlah__sum']
        volume = int(0 if volume is None else volume)
        volume_jual.append(volume)

        my_exp = i.barang_dalam_stack.all().aggregate(Min('expired'))['expired__min']
        my_exp = "-" if my_exp is None else my_exp
        expired.append(my_exp)

        inb_query = i.item_dalam_PO.filter(purchase_order__status=False)
        total_inbound = 0
        for j in inb_query:
            my_inbound = j.item_dalam_pengiriman.all().annotate(diterima=Coalesce(Sum('item_diterima__jumlah'), 0))
            my_inbound = my_inbound.aggregate(total=Sum(F('jumlah') - F('diterima')))['total']
            my_inbound = int(0 if my_inbound is None else my_inbound)
            total_inbound += my_inbound
        inbound.append(total_inbound)

    context = {
        "header": "Daftar Barang",
        "inventory": zip(query, jumlah_item, volume_jual, expired, inbound)
    }

    page_content = render_to_string('Inventory/index.html', context)

    return JsonResponse({
        'content': page_content,
        'title': 'Inventory Toko | Daftar Barang',
        'heading': 'Inventory'
    })


@login_required
def stock_gudang(request):
    # Get list stock
    query = stack.objects.all()
    list_stock = []
    for row in query:
        list_stock.append({
            "id": row.id,
            "nama": str(row.item),
            "gudang": row.gudang.nama,
            "satuan": row.item.satuan,
            "jumlah": row.jumlah,
            "expired": "-" if not row.expired else date_format(row.expired, "j N Y"),
            "keterangan": "" if not row.keterangan else row.keterangan
        })

    # Get list activiy
    list_activity = []
    num_days = 30
    timeframe = [localdate() - datetime.timedelta(num_days), localdate()]

    for row in item_masuk.objects.filter(parent__tanggal__range=timeframe):
        jumlah_akhir = row.jumlah_awal + row.jumlah
        record = {
            "id": row.id,
            "barang": str(row.item_parent),
            "ref": row.parent.pengiriman.purchase_order.ekspedisi,
            "gudang": row.gudang.nama,
            "tanggal": row.parent.tanggal,
            "waktu": row.parent.waktu,
            "jumlah": row.jumlah,
            "jumlah_awal": row.jumlah_awal,
            "jumlah_akhir": jumlah_akhir,
            "selisih": jumlah_akhir - row.jumlah_awal,
            "type": 1
        }
        list_activity.append(record)

    for row in item_keluar.objects.filter(parent__tanggal__range=timeframe):
        jumlah_akhir = row.jumlah_awal - row.jumlah
        record = {
            "id": row.id,
            "barang": str(row.item_parent),
            "ref": row.parent.transaksi.pelanggan,
            "gudang": row.gudang.nama,
            "tanggal": row.parent.tanggal,
            "waktu": row.parent.waktu,
            "jumlah": row.jumlah,
            "jumlah_awal": row.jumlah_awal,
            "jumlah_akhir": jumlah_akhir,
            "selisih": row.jumlah_awal - jumlah_akhir,
            "type": 0
        }
        list_activity.append(record)

    list_activity = sorted(list_activity, key=lambda d: (d['tanggal'], d['waktu']), reverse=True)

    # Compile page
    list_gudang = gudang.objects.all()
    context = {
        "header": "Stock Gudang",
        "list_gudang": list_gudang,
        'list_stock': list_stock,
        "list_activity": list_activity
    }

    page_content = render_to_string('Inventory/stock_gudang.html', context)

    return JsonResponse({
        'content': page_content,
        'title': 'Inventory Toko | Stock Gudang',
        'heading': 'Inventory',
    })


@login_required
def modify_item(request):
    my_id = request.GET.get('id')

    my_record = item.objects.get(id=my_id) if my_id else {
        "id": None, "nama": "", "harga": 0, "modal": 0,
        "ongkos": 0, "satuan": "", "keterangan": "", "archived": False
    }

    modal_content = render_to_string('Inventory/modify_item.html', {
        "item": my_record
    })
    return JsonResponse({'content': modal_content})


@login_required
def post_item(request):
    id_item = request.POST.get('id_item')
    nama = request.POST.get('nama')
    satuan = request.POST.get('satuan').title()
    harga = request.POST.get('harga')
    modal = request.POST.get('modal')
    ongkos = request.POST.get('ongkos')
    archived = request.POST.get('archived')
    keterangan = request.POST.get('keterangan')
    keterangan = None if keterangan == "" else keterangan

    if id_item != "None":
        updating = item.objects.get(id=id_item)
        updating = True
    else:
        updating = False

    if updating:
        target_item = item.objects.get(id=id_item)
        target_item.nama = nama
        target_item.harga = harga
        target_item.modal = modal
        target_item.ongkos = ongkos
        target_item.satuan = satuan
        target_item.archived = archived
        target_item.keterangan = keterangan
        target_item.save()
    else:
        new_item = item(nama=nama, satuan=satuan, harga=harga, modal=modal,
                        ongkos=ongkos, archived=archived, keterangan=keterangan)
        new_item.save()

    return JsonResponse({
        'message': f"Berhasil mengubah {nama}" if updating else f"Berhasil menambahkan {nama}"
    })


@login_required
def get_stack(request):
    my_id = request.GET.get('id')
    my_item = item.objects.get(id=my_id)

    stacks = my_item.barang_dalam_stack.all()

    item_activity = []

    for row in my_item.item_masuk.filter(parent__tanggal__range=
                                         [localdate() - datetime.timedelta(30), localdate()]):
        jumlah_akhir = row.jumlah_awal + row.jumlah
        record = {
            "id": row.id,
            "ref": row.parent.pengiriman.purchase_order.ekspedisi,
            "gudang": row.gudang,
            "tanggal": row.parent.tanggal,
            "waktu": row.parent.waktu,
            "jumlah": row.jumlah,
            "jumlah_awal": row.jumlah_awal,
            "jumlah_akhir": jumlah_akhir,
            "selisih": jumlah_akhir - row.jumlah_awal,
            "type": 1
        }
        item_activity.append(record)

    for row in my_item.item_keluar.filter(parent__tanggal__range=
                                          [localdate() - datetime.timedelta(30), localdate()]):
        jumlah_akhir = row.jumlah_awal - row.jumlah
        record = {
            "id": row.id,
            "ref": row.parent.transaksi.pelanggan,
            "gudang": row.gudang,
            "tanggal": row.parent.tanggal,
            "waktu": row.parent.waktu,
            "jumlah": row.jumlah,
            "jumlah_awal": row.jumlah_awal,
            "jumlah_akhir": jumlah_akhir,
            "selisih": row.jumlah_awal - jumlah_akhir,
            "type": 0
        }
        item_activity.append(record)

    item_activity = sorted(item_activity, key=lambda d: (d['tanggal'], d['waktu']), reverse=True)

    modal_content = render_to_string('Inventory/get_stack.html', {
        "item": my_item,
        "stacks": stacks,
        "item_activity": item_activity
    })
    return JsonResponse({'content': modal_content})


@login_required
def get_item_list(request):
    item_list = []
    for row in item.objects.filter(archived=False):
        item_list.append({
            "id": row.id, "nama": row.nama, "satuan": row.satuan,
            "harga": row.harga, "modal": row.modal, "label": str(row),
        })

    return JsonResponse({'item_list': item_list})


@login_required
def modify_stack(request):
    my_id = request.GET.get('id')

    my_record = stack.objects.get(id=my_id)

    modal_content = render_to_string('Inventory/modify_stack.html', {
        "stack": my_record
    })
    return JsonResponse({'content': modal_content})


@login_required
def post_stack(request):
    id_stack = request.POST.get('id_stack')
    expired = request.POST.get('expired')
    expired = None if expired == "" else expired
    jumlah = request.POST.get('jumlah')
    keterangan = request.POST.get('keterangan')
    keterangan = None if keterangan == "" else keterangan

    target_item = stack.objects.get(id=id_stack)
    target_item.expired = expired
    target_item.jumlah = jumlah
    target_item.keterangan = keterangan
    target_item.save()

    return JsonResponse({
        'message': f"Berhasil mengubah {target_item.item} - {target_item.gudang}."
    })


@login_required
def get_item_stock(request):
    my_id = request.GET.get('id')
    my_item = item.objects.get(id=my_id)
    stock = my_item.barang_dalam_stack.all().aggregate(total=Sum('jumlah'))['total']
    stock = 0 if stock == None else stock

    return JsonResponse({
        'stock': f"{number_format(stock, use_l10n=True)} {my_item.satuan}"
    })


@login_required

templates/Inventory/create_recap.html
{% load static %}
<h3>Buat Rekapan Inventory</h3>
<hr>
<form id="summary_form" class="form input_form mb-2" onsubmit="get_recap(event)">
    <h5>Jangka Waktu Rekap</h5>
    <div class="form-group">
        <div class="row">
            <div class="col-sm-12 col-md-5">
                <div class="input-group mb-2">
                    <span class="input-group-text text-bg-dark">Mulai</span>
                    <input class="form-control" type="date" name="mulai" id="mulai" value="{% now 'Y-m-d' %}" required>
                </div>
            </div>
            <div class="col-sm-12 col-md-5 mb-2">
                <div class="input-group">
                    <span class="input-group-text text-bg-dark">Sampai</span>
                    <input class="form-control" type="date" name="sampai" id="sampai">
                </div>
            </div>
            <div class="col-sm-12 col-md-2 text-end">
                <button type="submit" form="summary_form" class="btn btn-success" style="white-space: nowrap!important">Buat Rekapan</button>
            </div>
        </div>
    </div>
</form>
<hr>
<div id="recap_container"></div>


<script>
    const container = $('#recap_container');

    function get_recap() {
        event.preventDefault();

        $.ajax({
            type: "GET",
            url: "{% url "Inventory:get_recap" %}",
            headers: {'X-CSRFToken': csrf_token},
            data: {
                mulai: $('#mulai').val(), sampai: $('#sampai').val()
            },
            success: function (response) {
                $('#recap_container').html(response.content);
            },
            complete: function () {
                refactor_screen()
            }
        })
    }
</script>

templates/Inventory/index.html
{% load humanize %}
<div class="heading_container">
    <h3>{{ header }}</h3>
    <div class="button_container">
        <button onclick="get_modal('modify_item')" class="btn btn-success"><i class="fa-solid fa-plus"></i>&ensp;Tambahkan Barang</button>
    </div>
</div>
<hr>
<table class="table table-striped table-bordered border-dark table-hover w-100 dt_table">
        <thead class="table-dark">
            <th>No</th>
            <th>Barang</th>
            <th>Satuan</th>
            <th>Harga</th>
            <th class="min">Modal</th>
            <th class="min">Ongkos</th>
            <th>Jumlah</th>
            <th class="min">Inbound</th>
            <th class="min">Volume Jual</th>
            <th class="min">Expired</th>
            <th class="action_cell">Action</th>
        </thead>
        <tbody>
            {%  for item, jumlah_item, volume_jual, expired, inbound in inventory %}
                <tr ondblclick="get_modal('get_stack', {{ item.id }})"
                    oncontextmenu="get_modal('get_stack', {{ item.id }})">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.nama }}</td>
                    <td>{{ item.satuan }}</td>
                    <td class="num">Rp {{ item.harga|intcomma }}</td>
                    <td class="min num">Rp {{ item.modal|intcomma }}</td>
                    <td class="min num">Rp {{ item.ongkos|intcomma }}</td>
                    <td class="num">{{ jumlah_item|intcomma }}</td>
                    <td class="min num">{{ inbound|intcomma }}</td>
                    <td class="min num">{{ volume_jual|intcomma }}</td>
                    <td class="min">{{ expired }}</td>
                    <td class="action_cell">
                        <button class="btn btn-primary btn-sm" onclick="get_modal('get_stack', {{ item.id }})"
                        data-bs-title="Detail barang" data-bs-toggle="tooltip" data-bs-placement="bottom">
                        <i class="fa-solid fa-magnifying-glass"></i></button>

                        <button onclick="get_modal('modify_item', {{ item.id }})" class="btn btn-outline-dark btn-sm"
                        data-bs-title="Ubah barang" data-bs-toggle="tooltip" data-bs-placement="bottom">
                        <i class="fa-solid fa-file-pen"></i></button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
</table>

templates/Inventory/modify_item.html
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-fullscreen-sm-down">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">
                {% if item.id %}Ubah {{ item }}{% else %}Tambahkan Barang{% endif %}
            </h3>
            <button type="button" class="btn btn-close btn-close-white" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
            <form class="form m-0" id="modify_item_form" onsubmit="post_item(event)">
                <h5>Data Barang</h5>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-12 col-lg-8 mb-2">
                            <label class="form-label">Nama</label>
                            <input value="{{ item.nama }}" type="text" name="nama" id="nama"
                                       class="form-control" maxlength="32" required>
                        </div>
                        <div class="col-md-12 col-lg-4 mb-2">
                            <label class="form-label">Satuan</label>
                            <input value="{{ item.satuan }}" type="text" name="satuan" id="satuan"
                                       class="form-control" maxlength="12" required>
                        </div>
                    </div>
                </div>
                <hr>
                <h5>Harga Barang</h5>
                <div class="form-group mb-3">
                    <div class="row">
                        <div class="col-md-12 col-lg-4">
                            <label class="form-label">Harga Jual</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text">Rp</span>
                                <input value="{{ item.harga|cut:',' }}" type="number" name="harga" id="harga"
                                       class="form-control" min="0" step="500" required>
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-4">
                            <label class="form-label">Modal</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text">Rp</span>
                                <input value="{{ item.modal|cut:',' }}" type="number" name="modal" id="modal"
                                       class="form-control" min="0" step="500" required>
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-4">
                            <label class="form-label">Ongkos Kirim</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text">Rp</span>
                                <input value="{{ item.ongkos|cut:',' }}" type="number" name="ongkos" id="ongkos"
                                       class="form-control" min="0" step="500" required>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <h5>Informasi Tambahan</h5>
                <div class="form-group mb-3">
                    <div class="input-group">
                        <span class="input-group-text">Status</span>
                        <select name="archived" id="archived" class="form-select form-control">
                            <option value="0" {{ item.archived|yesno:"'', selected" }}>Aktif</option>
                            <option value="1" {{ item.archived|yesno:"selected, ''" }}>Tidak Aktif</option>
                        </select>
                    </div>
                </div>
                <div class="form-group mb-3">
                    <label class="form-label">Keterangan</label>
                    <textarea class="form-control" id="keterangan" name="keterangan" rows="2" maxlength="200">
{% if item.keterangan == "" or not item.keterangan %}{% else %}{{ item.keterangan }}{% endif %}</textarea>
                </div>
                <input type="hidden" id="id_item" name="id_item" value="{{ item.id }}">
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Tutup</button>
            <button form="modify_item_form" type="submit" class="btn btn-success">Simpan</button>
        </div>
    </div>
</div>

<script>
    function post_item() {
        event.preventDefault();

        const id_item = $('#id_item').val();
        const nama = $('#nama').val();
        const satuan = $('#satuan').val();
        const harga = parseInt($('#harga').val());
        const modal_harga = parseInt($('#modal').val());
        const ongkos = parseInt($('#ongkos').val());
        const archived = $('#archived').val();
        const keterangan = $('#keterangan').val();
        const text = (id_item == "")? `Tambahkan ${nama}?` : `Ubah data ${nama}?`;

        if (!confirm(text)) {return;}
        $.ajax({
            type: "POST",
            url: "{% url 'Inventory:post_item' %}",
            headers: {'X-CSRFToken': csrf_token},
            data: {
                id_item:id_item, nama:nama, satuan:satuan,
                harga:harga, modal:modal_harga, ongkos:ongkos,
                archived:archived, keterangan:keterangan
            },
            success: function (response) {
                alert(response.message)
                modal.modal('hide')
            },
            complete: function () {
                get_page(current_page, true)
                init_item_list()
            }
        });
        return false;
    }
</script>

templates/Inventory/modify_stack.html
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-fullscreen-sm-down">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">
                Ubah {{ stack.item }} - {{ stack.gudang }}
            </h3>
            <button type="button" class="btn btn-close btn-close-white" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
            <form class="form m-0" id="modify_stack_form" onsubmit="post_stack(event)">
                <h5>Data Barang</h5>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-12 col-lg-8 mb-2">
                            <label class="form-label">Barang</label>
                            <input value="{{ stack.item }}" type="text" class="form-control" disabled>
                        </div>
                        <div class="col-md-12 col-lg-4 mb-2">
                            <label class="form-label">Jumlah</label>
                            <input value="{{ stack.jumlah }}" type="number" name="jumlah" id="jumlah"
                               class="form-control" min="1">
                        </div>
                    </div>
                </div>
                <hr>
                <h5>Informasi Tambahan</h5>
                <div class="form-group mb-3">
                    <label class="form-label">Expired</label>
                    <input value="{{ stack.expired|date:'Y-m-d' }}" type="date" name="expired" id="expired" class="form-control">
                </div>
                <div class="form-group mb-3">
                    <label class="form-label">Keterangan</label>
                    <textarea class="form-control" id="keterangan" name="keterangan" rows="2" maxlength="200">
{% if stack.keterangan == "" or not stack.keterangan %}{% else %}{{ stack.keterangan }}{% endif %}</textarea>
                </div>
                <input type="hidden" id="id_stack" name="id_stack" value="{{ stack.id }}">
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Tutup</button>
            <button form="modify_stack_form" type="submit" class="btn btn-success">Simpan</button>
        </div>
    </div>
</div>

<script>
    function post_stack() {
        event.preventDefault();

        const id_stack = $('#id_stack').val();
        const jumlah = $('#jumlah').val();
        const expired = $('#expired').val()
        const keterangan = $('#keterangan').val();

        if (!confirm("Simpan perubahan?")) {return;}
        $.ajax({
            type: "POST",
            url: "{% url 'Inventory:post_stack' %}",
            headers: {'X-CSRFToken': csrf_token},
            data: {
                id_stack: id_stack, jumlah: jumlah, expired: expired, keterangan: keterangan
            },
            success: function (response) {
                alert(response.message)
                modal.modal('hide')
            },
            complete: function () {
                get_page(current_page, true)
            }
        });
        return false;
    }
</script>

templates/Inventory/payment_dialog.html
{% load humanize %}
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">
                Pembayaran {{ transaksi }}
            </h3>
            <button type="button" class="btn btn-close btn-close-white" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body" style="text-align: center">
            <h3>Metode Pembayaran</h3>
            <div class="container d-flex justify-content-center">
                <button class="btn btn-success mx-3" onclick="ubah_status({{ transaksi.id }}, 0, 0, 'Tunai')">Tunai</button>
                <button class="btn btn-primary mx-3" onclick="ubah_status({{ transaksi.id }}, 0, 0, 'Transfer')">Transfer</button>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Tutup</button>
        </div>
    </div>
</div>