ERP_Harapan/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.login_view, name='login'),
    path('login_verify/', views.login_verify, name='login_verify'),
    path('index/', views.index, name='index'),
    path('dashboard/', views.get_dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    path('end_session/', views.end_session, name='end_session'),

    path('inventory/', include("Inventory.urls")),
    path('purcashing/', include("Purchasing.urls")),
    path('sales/', include("Sales.urls")),
    path('management/', include("Management.urls")),
]

Inventory/urls.py
from django.urls import include, path
from django.shortcuts import render, redirect
from . import views

app_name = "Inventory"

urlpatterns = [
    path("", views.get_inventory, name="index"),
    path("modify_item/", views.modify_item, name="modify_item"),
    path("post_item/", views.post_item, name="post_item"),
    path("get_stack/", views.get_stack, name="get_stack"),
    path("get_item_list/", views.get_item_list, name="get_item_list"),
    path("get_item_stock/", views.get_item_stock, name="get_item_stock"),
    path("stock_gudang/", views.stock_gudang, name="stock_gudang"),
    path("modify_stack/", views.modify_stack, name="modify_stack"),
    path("post_stack/", views.post_stack, name="post_stack"),
    path("lunaskan/", views.lunaskan, name="lunaskan"),
    path("selesaikan/", views.selesaikan, name="selesaikan"),
    path("kembali_ke_draft/", views.kembali_ke_draft, name="kembali_ke_draft"),
    path("create_recap/", views.create_recap, name="create_recap"),
    path("get_recap/", views.get_recap, name="get_recap"),
    path("get_payment_dialog/", views.get_payment_dialog, name="get_payment_dialog"),
]

Management/urls.py
from django.urls import include, path
from django.shortcuts import render, redirect
from . import views

app_name = "Management"

urlpatterns = [
    path("", views.index, name="index"),
]

Purchasing/urls.py
from django.urls import include, path
from django.shortcuts import render, redirect
from . import views

app_name = "Purchasing"

urlpatterns = [
    path("", views.riwayat_purchase_order, name="index"),
    path("get_po/", views.get_po, name="get_po"),
    path("get_barang_masuk/", views.get_barang_masuk, name="get_barang_masuk"),
    path("get_pengiriman/", views.get_pengiriman, name="get_pengiriman"),
    path("modify_po/", views.modify_po, name="modify_po"),
    path("post_po/", views.post_po, name="post_po"),
    path("modify_pengiriman/", views.modify_pengiriman, name="modify_pengiriman"),
    path("post_pengiriman/", views.post_pengiriman, name="post_pengiriman"),
    path("terima_pengiriman/", views.terima_pengiriman, name="terima_pengiriman"),
    path("post_barang_masuk/", views.post_barang_masuk, name="post_barang_masuk"),
    path("riwayat_barang_masuk/", views.riwayat_barang_masuk, name="riwayat_barang_masuk"),
    path("riwayat_pengiriman/", views.riwayat_pengiriman, name="riwayat_pengiriman"),
]

Sales/urls.py
from django.urls import include, path
from django.shortcuts import render, redirect
from . import views

app_name = "Sales"

urlpatterns = [
    path("", views.transaction_records, name="index"),
    path("mofidy_transaksi/", views.mofidy_transaksi, name="mofidy_transaksi"),
    path("post_transaksi/", views.post_transaksi, name="post_transaksi"),
    path("get_transaksi/", views.get_transaksi, name="get_transaksi"),
    path("get_barang_keluar/", views.get_barang_keluar, name="get_barang_keluar"),
    path("create_bill/", views.create_bill, name="create_bill"),
    path("get_bill/", views.get_bill, name="get_bill"),
    path("riwayat_barang_keluar/", views.riwayat_barang_keluar, name="riwayat_barang_keluar"),
    path("keluarkan_barang/", views.keluarkan_barang, name="keluarkan_barang"),
    path("post_barang_keluar/", views.post_barang_keluar, name="post_barang_keluar"),
    path("get_print_dialog/", views.get_print_dialog, name="get_print_dialog"),
    path("post_print_req/", views.post_print_req, name="post_print_req"),
]

templates/General/dashboard.html
{% load humanize %}
<div class="heading_container">
    <h3>Dashboard Harian</h3>
    <div class="button_container">
        <button class="btn btn-primary" onclick="get_page('create_recap')">
            <i class="fa-solid fa-clipboard-list"></i>&ensp;Buat Rekapan
        </button>
        <a href="#head_transaksi" class="btn btn-light">Transaksi</a>
        <a href="#head_inventory" class="btn btn-dark">Inventory</a>
    </div>
</div>

<hr>

<div class="heading_container">
    <h3 id="head_transaksi">Transaksi Hari Ini</h3>
    <button onclick="get_modal('modify_transaksi')" class="btn btn-success"><i class="fa-solid fa-plus"></i>&ensp;Tambahkan Transaksi</button>
</div>

<div class="row mb-5">
    <div class="col-12">
        <table class="table table-striped table-bordered border-dark table-hover w-100 dt_table">
            <thead class="table-dark">
                <th>No</th>
                <th>Pelanggan</th>
                <th>Tanggal & Waktu</th>
                <th class="min">Pembayaran</th>
                <th class="min num">Harga Total</th>
                <th>Status</th>
                <th class="action_cell">Action</th>
            </thead>
            <tbody>
                {%  for record, status, harga_total in list_transaksi %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ record.pelanggan }}</td>
                        <td>{{ record.tanggal|date:'d M' }}, {{ record.waktu|time:'H:i' }}</td>
                        <td class="min">
                            {{ record.pembayaran }}
                            {% if record.metode_pembayaran %}
                            <br>
                            <span class="small text-nowrap">{{ record.metode_pembayaran }}, {{ record.tanggal_pembayaran }}</span>
                            {% endif %}
                        </td>
                        <td class="min num">Rp {{ harga_total|intcomma }}</td>
                        <td class="action_cell"><text class="status_box {{ status.color }}">{{ status.text }}</text></td>
                        <td class="action_cell">
                            <button onclick="get_modal('get_transaksi', {{ record.id }})" class="btn btn-primary btn-sm"
                            data-bs-title="Detail transaksi" data-bs-toggle="tooltip" data-bs-placement="bottom">
                            <i class="fa-solid fa-magnifying-glass"></i></button>

                            <button onclick="get_modal('get_print_dialog', {{ record.id }})" class="btn btn-dark btn-sm"
                            data-bs-title="Print nota" data-bs-toggle="tooltip" data-bs-placement="bottom">
                            <i class="fa-solid fa-print"></i></button>

                            {% if not status.selesai and not status.lunas %}
                            <button onclick="get_modal('modify_transaksi', {{ record.id }})" class="btn btn-outline-dark btn-sm"
                            data-bs-title="Ubah transaksi" data-bs-toggle="tooltip" data-bs-placement="bottom">
                            <i class="fa-solid fa-file-pen"></i></button>
                            {% endif %}

                            {% if not status.selesai %}
                            <button onclick="get_modal('keluarkan_barang', {{ record.id }})" class="btn btn-success btn-sm"
                            data-bs-title="Barang keluar" data-bs-toggle="tooltip" data-bs-placement="bottom">
                            <i class="fa-solid fa-truck-arrow-right"></i></button>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<hr>

<h3 id="head_inventory">Inventory</h3>
<div class="row mb-5">
    <div class="col-lg-6 col-sm-12">
        <h5>Barang Masuk</h5>
        <table class="table table-striped table-bordered border-dark table-hover w-100 dt_table">
            <thead class="table-dark">
                <th>No</th>
                <th>Pengiriman</th>
                <th>Tanggal<text class="min"> & Waktu</text></th>
                <th class="min">Admin</th>
                <th class="action_cell">Action</th>
            </thead>
            <tbody>
                {%  for record in list_masuk %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ record.pengiriman }}</td>
                        <td>{{ record.tanggal }}<text class="min">, {{ record.waktu }}</text></td>
                        <td class="min">{{ record.admin.username }}</td>
                        <td class="action_cell">
                            <button onclick="get_modal('get_barang_masuk', {{ record.pengiriman_id }}, 2)"
                            class="btn btn-primary btn-sm" data-bs-title="Lihat" data-bs-toggle="tooltip"
                            data-bs-placement="bottom"><i class="fa-solid fa-magnifying-glass"></i></button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-lg-6 col-sm-12">
        <h5>Barang Keluar</h5>
        <table class="table table-striped table-bordered border-dark table-hover w-100 dt_table">
            <thead class="table-dark">
                <th>No</th>
                <th>Pelanggan</th>
                <th>Tanggal<text class="min"> & Waktu</text></th>
                <th class="min">Admin</th>
                <th class="action_cell">Action</th>
            </thead>
            <tbody>
                {%  for record in list_keluar %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ record.transaksi.pelanggan }}</td>
                        <td>{{ record.tanggal }}<text class="min">, {{ record.waktu }}</text></td>
                        <td class="min">{{ record.admin.username }}</td>
                        <td class="action_cell">
                            <button onclick="get_modal('get_barang_keluar', {{ record.transaksi_id }}, 0)"
                            class="btn btn-primary btn-sm" data-bs-title="Lihat" data-bs-toggle="tooltip"
                            data-bs-placement="bottom"><i class="fa-solid fa-magnifying-glass"></i></button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

templates/General/footer.html
<div class="nav_container mt-auto" id="footer">
    <div class="d-flex align-items-center justify-content-between">
        <h5>ERP Toko Harapan Jaya</h5>
        <a class="btn btn-outline-light my-2" href="#header"><i class="fa-solid fa-arrow-up"></i>&ensp;Kembali ke Atas</a>
    </div>
    <div class="heading_container border-top border-light py-3">
        <a class="navbar-brand">Dashboard</a>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link btn active" onclick="get_page('dashboard')">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn" onclick="get_page('inventory')">Inventory</a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn" onclick="get_page('sales')">Sales</a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn" onclick="get_page('purchasing')">Pembelian</a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn" onclick="get_page('admin_dashboard')">Admin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn" onclick="get_modal('logout')">Logout</a>
            </li>
        </ul>
    </div>
</div>

templates/General/header.html
<nav class="navbar navbar-expand-lg shadow p-0" id="header">
    <div class="container-fluid nav_container heading_container">
        <a class="navbar-brand">Dashboard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#nav_main" aria-expanded="false" style="color: var(--light-primary-color)">
            <i class="fa-solid fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="nav_main">
        <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
            <li class="nav-item mx-3">
                <a class="nav-link active btn" aria-current="page" onclick="get_page('dashboard')">Dashboard</a>
            </li>
            <li class="nav-item mx-3 dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">Inventory&nbsp;</a>
                <ul class="dropdown-menu shadow">
                    <li><a class="dropdown-item btn" onclick="get_page('inventory')">
                        <span><i class="fa-solid fa-list"></i>&emsp;Daftar Barang</span>
                    </a></li>
                    <li><a class="dropdown-item btn" onclick="get_page('stock_gudang')">
                        <span><i class="fa-solid fa-warehouse"></i>&emsp;Stock Gudang</span>
                    </a></li>
                    <li><a class="dropdown-item btn" onclick="get_page('create_recap')">
                        <span><i class="fa-solid fa-clipboard-list"></i>&emsp;Buat Rekapan</span>
                    </a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item btn" onclick="get_modal('modify_item')">
                        <span><i class="fa-solid fa-plus"></i>&emsp;Tambahkan Barang</span>
                    </a></li>
                </ul>
            </li>
            <li class="nav-item mx-3 dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">Sales&nbsp;</a>
                <ul class="dropdown-menu shadow">
                    <li><a class="dropdown-item btn" onclick="get_page('sales')">
                        <span><i class="fa-solid fa-list"></i>&emsp;Riwayat Transaksi</span>
                    </a></li>
                    <li><a class="dropdown-item btn" onclick="get_page('create_bill')">
                        <span><i class="fa-solid fa-file-invoice"></i>&emsp;Buat Tagihan</span>
                    </a></li>
                    <li><a class="dropdown-item btn" onclick="get_page('riwayat_keluar')">
                        <span><i class="fa-solid fa-truck-arrow-right"></i>&emsp;Barang Keluar</span>
                    </a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item btn" onclick="get_modal('modify_transaksi')">
                        <span><i class="fa-solid fa-plus"></i>&emsp;Tambahkan Transaksi</span>
                    </a></li>
                </ul>
            </li>
            <li class="nav-item mx-3 dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">Pembelian&nbsp;</a>
                <ul class="dropdown-menu shadow">
                    <li><a class="dropdown-item btn" onclick="get_page('purchasing')">
                        <span><i class="fa-solid fa-list"></i>&emsp;Purchase Order</span>
                    </a></li>
                    <li><a class="dropdown-item btn" onclick="get_page('riwayat_pengiriman')">
                        <span><i class="fa-solid fa-truck"></i>&emsp;Pengiriman</span>
                    </a></li>

                    {# TODO:REKAPAN BIAYA EKSPEDISI #}
                    <li><a class="dropdown-item btn visually-hidden">
                        <span><i class="fa-solid fa-file-invoice-dollar"></i>&emsp;Hitung Tagihan</span>
                    </a></li>
                    <li><a class="dropdown-item btn" onclick="get_page('riwayat_masuk')">
                        <span><i class="fa-solid fa-truck-arrow-right flip"></i>&emsp;Barang Masuk</span>
                    </a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item btn" onclick="get_modal('modify_po')">
                        <span><i class="fa-solid fa-plus"></i>&emsp;Tambahkan PO</span>
                    </a></li>
                </ul>
            </li>
            <li class="nav-item mx-3 dropdown">
                <a class="nav-link dropdown-toggle" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">Admin&nbsp;</a>
                <ul class="dropdown-menu shadow">
                    <li><a class="dropdown-item btn" onclick="get_page('admin_dashboard')">
                        <span><i class="fa-solid fa-laptop-file"></i>&emsp;Dashboard Admin</span>
                    </a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item btn">
                        <span><i class="fa-solid fa-code-branch"></i>&emsp;Changelogs</span>
                    </a></li>
                    <li><a class="dropdown-item btn">
                        <span><i class="fa-solid fa-chalkboard-user"></i>&emsp;Sessions</span>
                    </a></li>
                </ul>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item ms-3 d-flex w-auto">
                <a class="nav-link active btn" onclick="get_modal('logout')">Logout</a>
            </li>
            {% endif %}
        </ul></div>
    </div>
</nav>

templates/General/index.html
{% extends "General/layout.html" %}
{% load static %}
<title>Dashboard</title>
{% block content %}
{{ content }}
{% endblock %}

templates/General/layout.html
{% load static %}
{% load i18n %}
{% language 'id' %}

<!DOCTYPE html>
<html>
<head>
    <!--META TAGS-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" type="image/png" href="{% static "logo_toko.png" %}">
    <!--PAGE TITLE-->
    <title>Toko Harapan Jaya</title>

    <!--JQUERY-->
    <script src="{% static 'jQuery/code.jquery.com_jquery-3.7.0.js' %}"></script>

    <!--BOOTSTRAP-->
    <link href='{% static 'bootstrap/css/bootstrap.css' %}' rel="stylesheet">
    <script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>

    <!--DATATABLES-->
    <link href='{% static 'datatables/datatables.css' %}' rel="stylesheet">
    <script src="{% static 'datatables/datatables.js' %}"></script>

    <!--JQUERY UI-->
    <link href='{% static 'jQueryUI/jquery-ui.css' %}' rel="stylesheet">
    <script src="{% static 'jQueryUI/jquery-ui.js' %}"></script>

    <!--LOCAL STYLES.CSS-->
    <link href='{% static 'styles.css' %}' rel="stylesheet">

    <!--FONTAWESOME(ICONS)-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>

<body>
{% if user.is_authenticated %}
    {% include "General/header.html" %}
{% endif %}
<div class="container-fluid my-3" id="root">
{% block content %} {% endblock %}
</div>
<div id="filler" style="background-color: transparent"></div>
{% if user.is_authenticated %}
    {% include "General/footer.html" %}
{% endif %}
</body>
</html>

<div class="modal fade" id="modal_template">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">Tutup</button>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'scripts.js' %}"></script>
{% if user.is_authenticated %}
<script>
    //FIXED VALUES AND ELEMENTS
    const csrf_token = '{{ csrf_token|escapejs }}';
    const root = $('#root');
    const modal = $('#modal_template');

    //URLS
    const modal_urls = {
        "modify_item": "{% url "Inventory:modify_item" %}",
        "get_stack": "{% url "Inventory:get_stack" %}",
        "modify_transaksi": "{% url "Sales:mofidy_transaksi" %}",
        "get_transaksi": "{% url "Sales:get_transaksi" %}",
        "get_barang_keluar": "{% url "Sales:get_barang_keluar" %}",
        "modify_stack": "{% url "Inventory:modify_stack" %}",
        "get_po": "{% url "Purchasing:get_po" %}",
        "get_barang_masuk": "{% url "Purchasing:get_barang_masuk" %}",
        "get_pengiriman": "{% url "Purchasing:get_pengiriman" %}",
        "modify_po": "{% url "Purchasing:modify_po" %}",
        "modify_pengiriman": "{% url "Purchasing:modify_pengiriman" %}",
        "terima_pengiriman": "{% url "Purchasing:terima_pengiriman" %}",
        "keluarkan_barang": "{% url "Sales:keluarkan_barang" %}",
        "logout": "{% url "logout" %}",
        "get_print_dialog": "{% url "Sales:get_print_dialog" %}",
        "get_payment_dialog": "{% url "Inventory:get_payment_dialog" %}",
    }
    const page_urls = {
        "dashboard": "{% url "dashboard" %}",
        "inventory":"{% url 'Inventory:index' %}",
        "stock_gudang":"{% url 'Inventory:stock_gudang' %}",
        "sales":"{% url "Sales:index" %}",
        "create_bill": "{% url "Sales:create_bill" %}",
        "riwayat_keluar": "{% url "Sales:riwayat_barang_keluar" %}",
        "purchasing": "{% url "Purchasing:index" %}",
        "riwayat_masuk": "{% url "Purchasing:riwayat_barang_masuk" %}",
        "riwayat_pengiriman": "{% url "Purchasing:riwayat_pengiriman" %}",
        "admin_dashboard": "{% url "Management:index" %}",
        "create_recap": "{% url "Inventory:create_recap" %}",
    }
    const util_urls = {
        "get_item_list":"{% url "Inventory:get_item_list" %}",
        "lunaskan":"{% url "Inventory:lunaskan" %}",
        "selesaikan":"{% url "Inventory:selesaikan" %}",
        "kembali_ke_draft":"{% url "Inventory:kembali_ke_draft" %}",
    }

    //GLOBAL VARIABLES
    let popover_list = [], tooltip_list = [];
    let item_list, new_list, list_stack, item_transaksi, item_po, item_pengiriman;
    let current_dialog;
    let current_page = 'dashboard';
    let current_table;

    const dt_settings = {
        "scrollX": true,
        "scrollY": true,
        "autoWidth": true,
        "searching": true,
        "select": true,
        "language": {
            "info" : "_START_ - _END_ dari _TOTAL_",
            "lengthMenu": "Tampilkan _MENU_",
            "search": "Cari:",
            "infoFiltered": "",
            "infoEmpty": "",
            "zeroRecords": "Data tidak ditemukan.",
            "paginate": {
                "sNext": "Setelah",
                "sPrevious": "Sebelum",
                "sLast": "Terakhir",
                "sFirst": "Pertama"
            }
        },
    };

    const dt_min_settings = {
        "scrollX": true,
        "scrollY": true,
        "autoWidth": true,
        "select": true,
        "info": false,
        "paging": false,
        "language": {
            "search": "Cari:",
            "infoFiltered": "",
            "infoEmpty": "",
            "zeroRecords": "Data tidak ditemukan.",
        },
    };
</script>
{% endif %}

{% endlanguage %}

templates/General/login.html
{% extends "General/layout.html" %}
{% load static %}

{% block title %}<title>Login Page</title>{% endblock %}

{% block content %}
<div class="container-fluid p-3 d-flex align-items-center justify-content-center">

    {% if message %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endif %}

    <form class="form input_form shadow border-dark border py-4 px-5" action="{% url 'login_verify' %}" method="POST"
        style="background-color: var(--dark-color); color:var(--light-primary-color)">
        {% csrf_token %}
        <h3>Login</h3>
        <hr>
        <label>Username</label>
        <input type="text" class="form-control" name="username">

        <br>

        <label>Password</label>
        <input type="password" class="form-control" name="password">

        <input style="margin-top:2rem" type="submit" class="btn btn-primary my-3" value="Log In">
    </form>
</div>
{% endblock %}

templates/General/logout.html
{% load humanize %}
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-fullscreen-sm-down">
    <div class="modal-content">
        <div class="modal-header">
            <figure class="figure">
                <h3 class="modal-title">
                    Akhiri Sesi {{ session.date|date:'d F Y' }}
                </h3>
                <h5 style="color: var(--primary-color)">Start:&ensp;{{ session.start_time|time:'H:i' }}</h5>
            </figure>
            <button type="button" class="btn btn-close btn-close-white" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
            <form class="form m-0" id="logout_form" method="POST" action="{% url "end_session" %}">
                <input type="hidden" id="session_id" name="session_id" value="{{ session.id }}">
                <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" name="username" id="username" value="{{ session.admin.username }}" readonly>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label>Jam Mulai</label>
                            <input type="text" class="form-control" name="jam_mulai" id="jam_mulai"
                                   value="{{ session.start_time }}" readonly>
                        </div>
                        <div class="col">
                            <label>Jam Selesai</label>
                            <input type="time" class="form-control" name="jam_selesai" id="jam_selesai"
                                   value="{% now 'H:i' %}" required>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-6">
                            <label>Cash Diterima</label>
                            <div class="input-group">
                                <span class="input-group-text">Rp</span>
                                <input type="number" class="form-control" name="cash_diterima" id="cash_diterima" step="500" required>
                            </div>
                        </div>
                        <div class="col-6">
                            <label>Cash Diambil</label>
                            <div class="input-group">
                                <span class="input-group-text">Rp</span>
                                <input type="number" class="form-control" name="cash_diambil" id="cash_diambil" step="500" required>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label>Keterangan</label>
                    <textarea class="form-control" name="keterangan" id="keterangan" rows="3"></textarea>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Tutup</button>
            <button form="logout_form" type="submit" class="btn btn-success">Simpan</button>
        </div>
    </div>
</div>