ERP_Harapan/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.login_view, name='login'),
    path('login_verify/', views.login_verify, name='login_verify'),
    path('index/', views.index, name='index'),
    path('dashboard/', views.get_dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    path('end_session/', views.end_session, name='end_session'),

    path('inventory/', include("Inventory.urls")),
    path('purcashing/', include("Purchasing.urls")),
    path('sales/', include("Sales.urls")),
    path('management/', include("Management.urls")),
]

Sales/urls.py
from django.urls import include, path
from django.shortcuts import render, redirect
from . import views

app_name = "Sales"

urlpatterns = [
    path("", views.transaction_records, name="index"),
    path("mofidy_transaksi/", views.mofidy_transaksi, name="mofidy_transaksi"),
    path("post_transaksi/", views.post_transaksi, name="post_transaksi"),
    path("get_transaksi/", views.get_transaksi, name="get_transaksi"),
    path("get_barang_keluar/", views.get_barang_keluar, name="get_barang_keluar"),
    path("create_bill/", views.create_bill, name="create_bill"),
    path("get_bill/", views.get_bill, name="get_bill"),
    path("riwayat_barang_keluar/", views.riwayat_barang_keluar, name="riwayat_barang_keluar"),
    path("keluarkan_barang/", views.keluarkan_barang, name="keluarkan_barang"),
    path("post_barang_keluar/", views.post_barang_keluar, name="post_barang_keluar"),
    path("get_print_dialog/", views.get_print_dialog, name="get_print_dialog"),
    path("post_print_req/", views.post_print_req, name="post_print_req"),
]

Sales/models.py
from django.db import models
from django.contrib.auth.models import User
from crum import get_current_user
from django.utils import timezone


class transaksi (models.Model):
    pelanggan = models.CharField(max_length=16)
    tanggal = models.DateField(default=timezone.localdate)
    waktu = models.TimeField(default=timezone.localtime)
    pembayaran = models.CharField(max_length=16)
    admin = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=get_current_user,
                              related_name="admin_transaksi")
    keterangan = models.CharField(max_length=200, null=True, blank=True)

    status_pembayaran = models.BooleanField(default=False)
    status = models.BooleanField(default=False)
    metode_pembayaran = models.CharField(max_length=8, null=True, default=None)
    tanggal_pembayaran = models.DateField(null=True, default=None)

    def __str__(self):
        try:
            name_str = f"{self.pelanggan}/{self.tanggal.strftime('%d %b')}"
        except:
            name_str = f"{self.pelanggan}/{self.tanggal}"

        return name_str


class item_transaksi (models.Model):
    transaksi = models.ForeignKey(transaksi, on_delete=models.CASCADE, related_name="item_dalam_transaksi")
    item = models.ForeignKey('Inventory.item', on_delete=models.DO_NOTHING, related_name="barang_terjual")
    jumlah = models.PositiveIntegerField()
    harga = models.PositiveIntegerField()
    keterangan = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.transaksi} | {self.item} @Rp{self.harga:,} x {self.jumlah:,}"


class print_request(models.Model):
    transaksi = models.ForeignKey(transaksi, on_delete=models.CASCADE)

    printer_key = models.CharField(max_length=15, null=False, blank=False)
    status = models.BooleanField(default=False)
    nominal_bayar = models.PositiveIntegerField(blank=True, null=True, default=0)
    date = models.DateField(default=timezone.localdate)
    time = models.TimeField(default=timezone.localtime)

    def __str__(self):
        return f"{self.transaksi} on {self.printer_key}, at {self.date} - {self.time}"

Sales/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from django.utils.formats import date_format, time_format
from django.utils.timezone import localdate
import datetime
import json

from django.db.models import Sum, Min, Q, F
from django.db.models.functions import Coalesce

from .models import transaksi, item_transaksi, print_request
from Inventory.models import stack, item_keluar, keluar_gudang, gudang


def map_status(status, payment):
    # Sudah selesai sudah bayar
    if status and payment:
        return {"color": "green", "text": "Selesai", "selesai": True, "lunas": True}
    # Sudah bayar, belum selesai
    if not status and payment:
        return {"color": "blue", "text": "Menunggu", "selesai": False, "lunas": True}
    if status and not payment:
        return {"color": "yellow", "text": "Hutang", "selesai": True, "lunas": False}
    if not status and not payment:
        return {"color": "gray", "text": "Draft", "selesai": False, "lunas": False}


@login_required
def transaction_records(request):
    timeframe = [localdate() - datetime.timedelta(60), localdate()]

    query = transaksi.objects.filter(tanggal__range=timeframe).order_by('-tanggal', '-waktu')
    status = []
    total_harga = []

    for row in query:
        my_total = row.item_dalam_transaksi.all().aggregate(total=Sum(F('jumlah') * F('harga')))['total']
        my_total = int(0 if my_total is None else my_total)
        total_harga.append(my_total)

        status.append(map_status(row.status, row.status_pembayaran))

    context = {
        "header": "Riwayat Transaksi",
        "riwayat": zip(query, status, total_harga)
    }

    page_content = render_to_string('Sales/index.html', context)

    return JsonResponse({
        'content': page_content,
        'title': 'Sales | Riwayat Transaksi',
        'heading': 'Sales'
    })


@login_required
def mofidy_transaksi(request):
    my_id = request.GET.get('id')
    my_record = transaksi.objects.get(id=my_id) if my_id else {
        "id": None, "pelanggan": "", "pembayaran": "Cash",
        "status_pembayaran": False, "status": False, "keterangan": ""
    }

    record_items = []
    if my_id != '':
        for row in my_record.item_dalam_transaksi.all():
            record_items.append({
                "id": row.item.id,
                "nama": row.item.nama,
                "jumlah": row.jumlah,
                "harga": row.harga,
                "harga_total": row.jumlah * row.harga,
                "keterangan": "" if row.keterangan is None else row.keterangan
            })

    modal_content = render_to_string('Sales/modify_transaksi.html', {
        "transaksi": my_record,
        "item_transaksi": json.dumps(record_items) if my_id != '' else None
    })
    return JsonResponse({'content': modal_content})


@login_required
def post_transaksi(request):
    id_transaksi = request.POST.get('id_transaksi')
    pelanggan = request.POST.get('pelanggan').title()
    pembayaran = request.POST.get('pembayaran').split(" - ")
    keterangan = request.POST.get('keterangan')
    keterangan = None if keterangan == "" else keterangan

    status_pembayaran = True if "Cash" in pembayaran else False
    status = True if "Toko" in pembayaran else False

    item_dalam_transaksi = json.loads(request.POST.get('item_transaksi'))

    target_item = None

    if id_transaksi != "None":
        target_item = transaksi.objects.get(id=id_transaksi)
        updating = True
    else:
        updating = False

    if updating:
        target_item.pelanggan = pelanggan
        try:
            target_item.pembayaran = f"{pembayaran[0]} - {pembayaran[2]}"
            target_item.metode_pembayaran = pembayaran[1]
            target_item.tanggal_pembayaran = timezone.localtime()
        except:
            target_item.pembayaran = f"{pembayaran[0]} - {pembayaran[1]}"
        target_item.keterangan = keterangan
        target_item.status = status
        target_item.status_pembayaran = status_pembayaran

        target_item.save()
    else:
        target_item = transaksi(pelanggan=pelanggan, status=status, status_pembayaran=status_pembayaran, keterangan=keterangan,
                                pembayaran=f"{pembayaran[0]} - {pembayaran[2]}" if status_pembayaran else f"{pembayaran[0]} - {pembayaran[1]}",
                                metode_pembayaran=pembayaran[1] if status_pembayaran else None,
                                tanggal_pembayaran=timezone.localtime() if status_pembayaran else None
                                )
        target_item.save()

    if updating:
        target_item.item_dalam_transaksi.all().delete()

    for row in item_dalam_transaksi:
        new_item = item_transaksi(transaksi=target_item, item_id=row['id'], jumlah=row['jumlah'], harga=row['harga'],
                                  keterangan="" if row['keterangan'] is None else row['keterangan'])
        new_item.save()

    return JsonResponse({
        'message': f"Berhasil mengubah {target_item}" if updating else f"Berhasil menambahkan {target_item}"
    })


@login_required
def get_transaksi(request):
    my_id = request.GET.get('id')

    my_record = transaksi.objects.get(id=my_id)
    my_items = my_record.item_dalam_transaksi.all()

    try:
        d_pembayaran = f"{my_record.metode_pembayaran} - {date_format(my_record.tanggal_pembayaran)}"
    except:
        d_pembayaran = "Belum Dibayar"

    context = {
        "transaksi": {
            "id": my_id,
            "pembayaran": my_record.pembayaran,
            "d_pembayaran": d_pembayaran,
            "header": f"{my_record.pelanggan} | {date_format(my_record.tanggal)}, "
                      f"{time_format(my_record.waktu)} | Admin: {my_record.admin.username}",
            "status": map_status(my_record.status, my_record.status_pembayaran),
            "keterangan": my_record.keterangan
        },
        "item_transaksi": my_items,
        "grand_total": my_items.aggregate(total=Sum(F('jumlah') * F('harga')))['total'],
        "ada_keterangan": my_items.exclude(keterangan__exact='').exclude(keterangan__isnull=True).exists()
    }

    modal_content = render_to_string('Sales/get_transaksi.html', context)
    return JsonResponse({'content': modal_content})


@login_required
def get_barang_keluar(request):
    my_id = request.GET.get('id')
    type = request.GET.get('type')

    # Buffer values
    my_transaksi = None
    my_object = None
    barang_keluar = []

    # Get all from parent
    if type == '0':
        my_transaksi = transaksi.objects.get(id=my_id)

        for row in my_transaksi.record_keluar.all():
            buffer = {
                "record": row,
                "items": row.item_dalam_record_keluar.all()
            }
            barang_keluar.append(buffer)
    # Get object by id
    elif type == '1':
        my_object = item_keluar.objects.get(id=my_id).parent
        my_transaksi = my_object.transaksi

        barang_keluar.append({
            "record": my_object,
            "items": my_object.item_dalam_record_keluar.all()
        })

    context = {
        "id": my_transaksi.id,
        "type": type,
        "header": f"{my_transaksi.pelanggan} | {date_format(my_transaksi.tanggal)}, {time_format(my_transaksi.waktu)}",
        "item_keluar": barang_keluar
    }

    modal_content = render_to_string('Sales/get_barang_keluar.html', context)
    return JsonResponse({'content': modal_content})


@login_required
def create_bill(request):
    context = {
        "default_start": date_format(localdate() - datetime.timedelta(days=30), 'Y-m-01')
    }

    page_content = render_to_string('Sales/create_bill.html', context)

    return JsonResponse({
        'content': page_content,
        'title': 'Sales | Buat Tagihan',
        'heading': 'Sales'
    })


@login_required
def get_bill(request):
    pelanggan = request.GET.get('pelanggan')
    mulai = request.GET.get('mulai')
    sampai = request.GET.get('sampai')

    list_item = []
    list_total = []

    list_transaksi = transaksi.objects.filter(pelanggan__contains=pelanggan,
                                              tanggal__range=[mulai, sampai]).order_by('-tanggal', '-waktu')

    list_hari = list_transaksi.values('tanggal').annotate(harga_total=
                                                          Coalesce(Sum(F('item_dalam_transaksi__jumlah') * F(
                                                              'item_dalam_transaksi__harga')), 0)).order_by('tanggal')

    for row in list_transaksi:
        list_item.append(row.item_dalam_transaksi.all())
        list_total.append(row.item_dalam_transaksi.all().aggregate(total=Sum(F('jumlah') * F('harga')))['total'])

    context = {
        "list_transaksi": zip(list_transaksi, list_item, list_total),
        "list_hari": list_hari,
        "grand_total": list_hari.aggregate(total=Sum('harga_total'))['total']
    }

    content = render_to_string('Sales/get_bill.html', context)
    return JsonResponse({
        'content': content
    })


@login_required
def riwayat_barang_keluar(request):
    context = {
        "header": "Riwayat Barang Keluar",
        "riwayat": keluar_gudang.objects.all().order_by('-tanggal', '-waktu')[:200]
    }

    page_content = render_to_string('Sales/riwayat_barang_keluar.html', context)

    return JsonResponse({
        'content': page_content,
        'title': 'Sales | Riwayat Barang Keluar',
        'heading': 'Sales'
    })


@login_required
def keluarkan_barang(request):
    my_id = request.GET.get('id')

    my_record = transaksi.objects.get(id=my_id)

    available_gudang = []
    list_item_transaksi = []
    for row in my_record.item_dalam_transaksi.all():
        list_item_transaksi.append({"id": row.id, "parent_id": row.item.id,

templates/Sales/create_bill.html
<h3>Buat Tagihan /  Rekapan Penjualan</h3>
<hr>
<form id="bill_form" class="form input_form mb-2" onsubmit="get_bill(event)">
    <h5>Pelanggan</h5>
    <div class="form-group mb-2">
        <label class="form-label">Nama</label>
        <input class="form-control" type="text" id="pelanggan" name="pelanggan"
               placeholder="Nama pelanggan..." required>
    </div>
    <h5>Jangka Waktu Rekap</h5>
    <div class="row">
        <div class="col-sm-12 col-md-5 mb-2">
            <div class="input-group">
                <span class="input-group-text text-bg-dark">Mulai</span>
                <input class="form-control" type="date" name="mulai" id="mulai" value="{{ default_start }}" required>
            </div>
        </div>
        <div class="col-sm-12 col-md-5 mb-2">
            <div class="input-group">
                <span class="input-group-text text-bg-dark">Sampai</span>
                <input class="form-control" type="date" name="sampai" id="sampai" value="{% now 'Y-m-d' %}" required>
            </div>
        </div>
        <div class="col-sm-12 col-md-2 text-end">
            <button type="submit" form="summary_form" class="btn btn-success" style="white-space: nowrap!important">Buat Rekapan</button>
        </div>
    </div>
</form>
<hr>
<div id="recap_container"></div>

<script>
    function get_bill() {
        event.preventDefault();

        $.ajax({
            type: "GET",
            url: "{% url "Sales:get_bill" %}",
            headers: {'X-CSRFToken': csrf_token},
            data: {
                pelanggan: $('#pelanggan').val(), mulai: $('#mulai').val(), sampai: $('#sampai').val()
            },
            success: function (response) {
                $('#recap_container').html(response.content);
            },
            complete: function () {
                location.href = "#recap_container";
            }
        })
    }
</script>

templates/Sales/get_barang_keluar.html
{% load humanize %}
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable
            modal-fullscreen-md-down modal-xl">
    <div class="modal-content">
        <div class="modal-header heading_container">
            <div class="modal-title">
                <h3>Barang Keluar</h3>
                <h5>{{ header }}</h5>
            </div>

            <div class="button_container">
                {% if type == '1' %}
                    <button onclick="get_modal('get_barang_keluar', {{ id }}, 0)" class="btn btn-dark"><i class="fa-solid fa-arrows-up-down"></i>&ensp;Semua</button>
                {% endif %}
                <button onclick="get_modal('get_transaksi', {{ id }})" class="btn btn-light"><i class="fa-solid fa-share flip"></i>&ensp;Ke Transaksi</button>
            </div>
        </div>
        <div class="modal-body">
            <div class="row p-2">
                <table class="table table-striped table-bordered border-dark table-hover w-100">
                {% if type == '1' %}
                    <p style="font-style: italic">* Tidak menampilkan semua. Click tombol diatas untuk mengubah.</p>
                {% endif %}
                    <thead class="table-dark">
                        <tr>
                            <th rowspan="2">Tanggal & Waktu</th>
                            <th rowspan="2">Barang</th>
                            <th rowspan="2">Gudang</th>
                            <th colspan="2" class="action_cell">Jumlah</th>
                        </tr>
                        <tr>
                            <th class="action_cell">Nota</th>
                            <th class="action_cell">Keluar</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for i in item_keluar %}
                        <tr>
                            <td colspan="5" class="fw-bold">{{ i.record.tanggal }}, {{ i.record.waktu }} | Admin: {{ i.record.admin.username }}</td>
                        </tr>
                        {% for j in i.items %}
                            <tr>
                                <td></td>
                                <td>{{ j.item_parent }}</td>
                                <td>{{ j.gudang.nama }}</td>
                                <td class="num">{{ j.item.jumlah|intcomma }}</td>
                                <td class="num">{{ j.jumlah|intcomma }}</td>
                            </tr>
                        {% endfor %}
                    {% empty %}
                        <tr class="action_cell"><td colspan="6">Tidak ada barang.</td></tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Tutup</button>
        </div>
    </div>
</div>

templates/Sales/keluarkan_barang.html
{% load humanize %}
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-fullscreen">
    <div class="modal-content">
        <div class="modal-header heading_container">
            <figure class="figure">
                <h3 class="modal-title">
                    Kelurkan barang untuk {{ transaksi }}
                </h3>
                <h5 style="color: var(--primary-color)">
                    Transaksi: {{ transaksi.pelanggan }}, {{ transaksi.tanggal }} | Pembayaran: {{ transaksi.pembayaran }}</h5>
                <figcaption class="figure-caption mt-2" style="color: var(--light-primary-color)">{{ pengiriman.keterangan|default_if_none:"" }}</figcaption>
            </figure>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-12 col-lg-8 mb-2">
                    <div class="heading_container input_heading success mb-2">
                        <h5>Barang dalam Transaksi</h5>
                        <input type="hidden" value="{{ transaksi.id }}" id="id_transaksi">
                        <button onclick="post_barang_keluar()" type="button" class="btn btn-success">Simpan</button>
                    </div>
                    <table class="table table-striped table-bordered border-dark table-hover w-100">
                        <thead class="table-dark">
                            <th>No</th>
                            <th>Barang</th>
                            <th>Gudang</th>
                            <th>Jumlah</th>
                            <th>Keluar</th>
                            <th>Keterangan</th>
                            <th class="action_cell">Action</th>
                        </thead>
                        <tbody>
                            {% for item, list in item_transaksi %}
                            <tr id="form-{{ item.id }}">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ item.nama }}</td>
                                <td class="input_cell">
                                    <select class="form-control form-select" id="gudang">
                                        <option value=""></option>
                                        {% for gudang in list %}
                                            <option value="{{ gudang.id }}">{{ gudang.nama }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                                <td class="num">{{ item.jumlah|intcomma }}</td>
                                <td class="input_cell">
                                    <input id="jumlah" class="form-control" type="number" min="0" value="{{ item.jumlah }}">
                                </td>
                                <td class="input_cell">
                                    <textarea id="keterangan" class="form-control " rows="1" maxlength="200"></textarea>
                                </td>
                                <td class="action_cell">
                                    <button onclick="tambahkan_barang({{ item.id }}, {{ item.parent_id }})" type="button" class="btn btn-success btn-sm">
                                    <i class="fa-solid fa-plus"></i></button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="col-md-12 col-lg-4 mt-5 mt-lg-0">
                    <h5>Barang Keluar</h5>
                    <table id="nota" class="table table-striped table-bordered border-dark table-hover w-100">
                        <thead class="table-dark">
                            <th>Barang</th>
                            <th>Gudang</th>
                            <th>Jumlah</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            <tr><td style="text-align: center" colspan="5">Belum ada barang keluar.</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Tutup</button>
            <button onclick="post_barang_keluar()" type="button" class="btn btn-success">Simpan</button>
        </div>
    </div>
</div>

<script>
    $(function () {
        item_keluar = []

        map_gudang = {
        {% for gudang in list_gudang %}
            {{ gudang.id }}:'{{ gudang.nama }}',
        {% endfor %}
        }

        map_barang = {
        {% for item in list_item %}
            {{ item.id }}:['{{ item.item }}', {{ item.jumlah }}],
        {% endfor %}
        }
    })

    modal.one('hidden.bs.modal', function () {
        if (item_keluar.length > 0){
            if(!confirm("Simpan data?")){
                item_keluar =[]
            }
        }
    })

    function validate_input(id, id_parent, jumlah, gudang_id) {
        if (gudang_id==="" || isNaN(jumlah)) {
            alert("Data barang tidak valid. Tolong diperiksa lagi.")
            return false
        }

        const sum_jumlah = item_keluar.reduce(function (sum, current) {
            if (current.item_parent_id === id_parent) {
                return sum + current.jumlah
            } else {
                return sum;
            }
        }, 0);

        if (jumlah + sum_jumlah > map_barang[id][1]) {
            alert("Jumlah keluar melebihi jumlah transaksi.")
            return false
        }

        return true
    }

    function tambahkan_barang(id, id_parent) {
        const parent = $(`#form-${id}`)
        let values = []

        parent.find('td.input_cell .form-control').each(function() {
            values.push($(this).val())
        })

        const keterangan = values.pop();
        const jumlah = parseInt(values.pop());
        const gudang_id = values.pop()

        if (!validate_input(id, id_parent, jumlah, gudang_id)) {return}

        item_keluar.push({
            keterangan:keterangan,
            jumlah:jumlah,
            gudang_id:gudang_id,
            item_parent_id:id_parent,
            item_id:id
        })

        parent.find('td.input_cell .form-control').each(function() {
            if ($(this).attr('type') === 'number') {
                $(this).val(0)
            } else {
                $(this).val('')
            }
        })
        parent.find('td.input_cell .form-control:first').focus()
        reload_table()
    }

    function hapus_barang(index) {
        item_keluar.splice(index, 1)
        reload_table()
    }

    function reload_table() {
        $('#nota tbody').empty();
        if (item_keluar.length == 0) {
            $('#nota > tbody:last-child').append('<tr><td class="action_cell" colspan="5">Belum ada barang masuk.</td></tr>'); return;
        }

        for (let i = 0; i < item_keluar.length; i++) {
            item = item_keluar[i]
            $('#nota > tbody:last-child').append(`
            <tr class="${(i%2==0)? 'even' : 'odd'}">

                <td>${map_barang[item.item_id][0]}</td>
                <td>${map_gudang[item.gudang_id]}</td>
                <td class="num">${item.jumlah.toLocaleString()}</td>
                <td class="action_cell">
                    <button onclick="hapus_barang(${i})" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i></button>
                    ${(item.keterangan == "")? '' :
                    `
                    <button class="btn btn-primary btn-sm" data-bs-container="body" data-bs-toggle="popover"
                    data-bs-placement="bottom" title="Keterangan" data-bs-content="${item.keterangan}">
                    <i class="fa-solid fa-magnifying-glass"></i></button>
                    `}
                </td>
            </tr>`);
        }
        init_popover(modal)
    }

    function post_barang_keluar() {
        event.preventDefault();
        if (item_keluar.length == 0) {
            alert("Belum memasukkan barang.");
            return;
        }

        const id_transaksi = $('#id_transaksi').val()

        if (!confirm("Simpan catatan barang keluar?")) {return;}
        $.ajax({
            type: "POST",
            url: "{% url 'Sales:post_barang_keluar' %}",
            headers: {'X-CSRFToken': csrf_token},
            data: {
                id_transaksi:id_transaksi, item_keluar:JSON.stringify(item_keluar)
            },
            success: function (response) {
                alert(response.message)
                modal.modal('hide')
            },
            complete: function () {
                item_keluar = []
                get_page(current_page, true)
            }
        });
        return false;
    }
</script>

templates/Sales/print_dialog.html
{% load humanize %}
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">
                Print Transaksi {{ transaksi }}
            </h3>
            <button type="button" class="btn btn-close btn-close-white" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body" style="text-align: center">
            <form class="form mx-auto" id="update_nominal_bayar">
                <h3>Nominal Bayar</h3>
                <h5>Total Harga Transaksi: Rp{{ harga_total|intcomma }}</h5>
                <input type="hidden" id="id_transaksi" value="{{ transaksi.id }}">
                <div class="input-group">
                    <span class="input-group-text">Rp</span>
                    <input type="number" class="form-control" name="nominal_bayar"
                           id="nominal_bayar" min="0" step="500">
                    <input class="btn btn-success" type="submit" value="Masukkan">
                </div>
            </form>
            <hr>
            <div class="row">
                <div class="col-4">
                    <button class="btn btn-primary" onclick="post_print_req('HJ-TR-001')">Kasir Toko</button>
                </div>
                <div class="col-4">
                    <button class="btn btn-primary" onclick="post_print_req('HJ-DM-001')">Kontan Toko</button>
                </div>
                <div class="col-4">
                    <button class="btn btn-primary" onclick="post_print_req('HJ-DM-002')">Kontan Kantor</button>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Tutup</button>
        </div>
    </div>
</div>

<script>
    function post_print_req(printer_key) {
        const id_transaksi = $('#id_transaksi').val()
        let nominal_bayar = parseInt($('#nominal_bayar').val())
        nominal_bayar = (isNaN(nominal_bayar)? 0 : nominal_bayar)
        $.ajax({
            type: "POST",
            url: "{% url 'Sales:post_print_req' %}",
            headers: {'X-CSRFToken': csrf_token},
            data: {
                id_transaksi:id_transaksi, nominal_bayar:nominal_bayar, printer_key:printer_key
            },
            success: function (response) {
                modal.modal('hide')
            }
        });
    }
</script>

templates/Sales/riwayat_barang_keluar.html
{% load humanize %}
<div class="heading_container">
    <h3>{{ header }}</h3>
</div>
<hr>
<table class="table table-striped table-bordered border-dark table-hover w-100 dt_table">
        <thead class="table-dark">
            <th>No</th>
            <th>Pelanggan</th>
            <th>Tanggal<text class="min"> & Waktu</text></th>
            <th class="min">Admin</th>
            <th class="action_cell">Action</th>
        </thead>
        <tbody>
            {%  for record in riwayat %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ record.transaksi.pelanggan }}</td>
                    <td>{{ record.tanggal }}<text class="min">, {{ record.waktu }}</text></td>
                    <td class="min">{{ record.admin.username }}</td>
                    <td class="action_cell">
                        <button onclick="get_modal('get_barang_keluar', {{ record.transaksi_id }}, 0)" class="btn btn-primary btn-sm"><i class="fa-solid fa-magnifying-glass"></i></button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
</table>