ERP_Harapan/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.login_view, name='login'),
    path('login_verify/', views.login_verify, name='login_verify'),
    path('index/', views.index, name='index'),
    path('dashboard/', views.get_dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    path('end_session/', views.end_session, name='end_session'),

    path('inventory/', include("Inventory.urls")),
    path('purcashing/', include("Purchasing.urls")),
    path('sales/', include("Sales.urls")),
    path('management/', include("Management.urls")),
]

Purchasing/urls.py
from django.urls import include, path
from django.shortcuts import render, redirect
from . import views

app_name = "Purchasing"

urlpatterns = [
    path("", views.riwayat_purchase_order, name="index"),
    path("get_po/", views.get_po, name="get_po"),
    path("get_barang_masuk/", views.get_barang_masuk, name="get_barang_masuk"),
    path("get_pengiriman/", views.get_pengiriman, name="get_pengiriman"),
    path("modify_po/", views.modify_po, name="modify_po"),
    path("post_po/", views.post_po, name="post_po"),
    path("modify_pengiriman/", views.modify_pengiriman, name="modify_pengiriman"),
    path("post_pengiriman/", views.post_pengiriman, name="post_pengiriman"),
    path("terima_pengiriman/", views.terima_pengiriman, name="terima_pengiriman"),
    path("post_barang_masuk/", views.post_barang_masuk, name="post_barang_masuk"),
    path("riwayat_barang_masuk/", views.riwayat_barang_masuk, name="riwayat_barang_masuk"),
    path("riwayat_pengiriman/", views.riwayat_pengiriman, name="riwayat_pengiriman"),
]

Sales/urls.py
from django.urls import include, path
from django.shortcuts import render, redirect
from . import views

app_name = "Sales"

urlpatterns = [
    path("", views.transaction_records, name="index"),
    path("mofidy_transaksi/", views.mofidy_transaksi, name="mofidy_transaksi"),
    path("post_transaksi/", views.post_transaksi, name="post_transaksi"),
    path("get_transaksi/", views.get_transaksi, name="get_transaksi"),
    path("get_barang_keluar/", views.get_barang_keluar, name="get_barang_keluar"),
    path("create_bill/", views.create_bill, name="create_bill"),
    path("get_bill/", views.get_bill, name="get_bill"),
    path("riwayat_barang_keluar/", views.riwayat_barang_keluar, name="riwayat_barang_keluar"),
    path("keluarkan_barang/", views.keluarkan_barang, name="keluarkan_barang"),
    path("post_barang_keluar/", views.post_barang_keluar, name="post_barang_keluar"),
    path("get_print_dialog/", views.get_print_dialog, name="get_print_dialog"),
    path("post_print_req/", views.post_print_req, name="post_print_req"),
]

Purchasing/models.py
from django.db import models
from django.contrib.auth.models import User
from crum import get_current_user


class purchase_order(models.Model):
    nomor_invoice = models.CharField(max_length=16)
    penjual = models.CharField(max_length=16)
    ekspedisi = models.CharField(max_length=16, null=True)
    tanggal = models.DateField()
    jatuh_tempo = models.DateField()
    status_pembayaran = models.BooleanField(default=False)
    status = models.BooleanField(default=False)
    keterangan = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        try:
            name_str = f"{self.penjual}/{self.ekspedisi}/{self.tanggal.strftime('%d %b')}"
        except:
            name_str = f"{self.penjual}/{self.ekspedisi}/{self.tanggal}"
        return name_str


class item_PO(models.Model):
    purchase_order = models.ForeignKey(purchase_order, on_delete=models.CASCADE, related_name="item_PO")
    item = models.ForeignKey('Inventory.item', on_delete=models.DO_NOTHING, related_name="item_dalam_PO")

    harga = models.PositiveIntegerField()
    jumlah = models.PositiveIntegerField()
    keterangan = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.purchase_order}\t{self.item} QTY: {self.jumlah:,}"


class pengiriman(models.Model):
    purchase_order = models.ForeignKey(purchase_order, on_delete=models.CASCADE, related_name="pengiriman_dalam_PO")
    admin = models.ForeignKey(User, default=get_current_user, on_delete=models.DO_NOTHING)

    tanggal = models.DateField()
    tanggal_sampai = models.DateField(null=True, blank=True)
    keterangan = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        myDict = {}
        for index, entry in enumerate(pengiriman.objects.filter(purchase_order=self.purchase_order)):
            myDict[entry] = index
        return f"{self.purchase_order}/{myDict[self] + 1:,}"


class item_pengiriman(models.Model):
    pengiriman = models.ForeignKey(pengiriman, on_delete=models.CASCADE, related_name="item_pengiriman")
    item_PO = models.ForeignKey(item_PO, on_delete=models.CASCADE, related_name="item_dalam_pengiriman")

    ongkos = models.PositiveIntegerField()
    jumlah = models.PositiveIntegerField()
    keterangan = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.pengiriman} | {self.item_PO.item} ({self.jumlah:,})"

Purchasing/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required

from django.utils.formats import date_format, number_format
from django.utils.timezone import localdate
import datetime
import json

from django.db.models import Sum, Min, Q, F
from django.db.models.functions import Coalesce

from .models import purchase_order, pengiriman, item_PO, item_pengiriman
from Inventory.models import item_masuk, gudang, masuk_gudang, stack


def map_status(status, payment):
    # Sudah selesai sudah bayar
    if status and payment:
        return {"color": "green", "text": "Selesai", "selesai": True, "lunas": True}
    # Sudah bayar, belum selesai
    if not status and payment:
        return {"color": "blue", "text": "Menunggu", "selesai": False, "lunas": True}
    if status and not payment:
        return {"color": "yellow", "text": "Hutang", "selesai": True, "lunas": False}
    if not status and not payment:
        return {"color": "gray", "text": "Draft", "selesai": False, "lunas": False}


@login_required
def riwayat_purchase_order(request):
    query = purchase_order.objects.all().order_by('-tanggal')[:200]
    status = []
    total_harga = []

    for row in query:
        my_total = row.item_PO.all().aggregate(total=Sum(F('jumlah') * F('harga')))['total']
        my_total = int(0 if my_total is None else my_total)
        total_harga.append(my_total)

        status.append(map_status(row.status, row.status_pembayaran))

    context = {
        "header": "Riwayat PO / Invoice",
        "riwayat": zip(query, status, total_harga)
    }

    page_content = render_to_string('Purchasing/index.html', context)

    return JsonResponse({
        'content': page_content,
        'title': 'Pembelian | Riwayat PO',
        'heading': 'Pembelian'
    })


@login_required
def get_po(request):
    my_id = request.GET.get('id')

    my_record = purchase_order.objects.get(id=my_id)
    my_items = my_record.item_PO.all().annotate(diterima=Coalesce(Sum('item_dalam_pengiriman__item_diterima__jumlah'), 0))

    context = {
        "purchase_order": {
            "id": my_id,
            "nomor": my_record.nomor_invoice,
            "header": f"{my_record.penjual} | {date_format(my_record.tanggal)} | {my_record.ekspedisi}",
            "status": map_status(my_record.status, my_record.status_pembayaran),
            "keterangan": "" if my_record.keterangan is None else my_record.keterangan
        },
        "item_po": my_items,
        "grand_total": my_items.aggregate(total=Sum(F('diterima') * F('harga')))['total'],
        "ada_keterangan": my_items.exclude(keterangan__exact='').exclude(keterangan__isnull=True).exists()
    }

    modal_content = render_to_string('Purchasing/get_po.html', context)
    return JsonResponse({'content': modal_content})


@login_required
def get_barang_masuk(request):
    my_id = request.GET.get('id')
    type = request.GET.get('type')

    # Buffer values
    my_po = None
    my_object = None
    list_pengiriman = []

    # Get all pengiriman from purchase order
    if type == '0':
        my_po = purchase_order.objects.get(id=my_id)

        for row in my_po.pengiriman_dalam_PO.all():
            list_masuk = []
            for i in row.record_masuk.all():
                for j in i.item_dalam_record_masuk.all():
                    list_masuk.append({
                        "nama": str(j.item_parent),
                        "gudang": j.gudang.nama,
                        "jumlah": j.item.jumlah,
                        "diterima": j.jumlah
                    })

            list_pengiriman.append({
                "record": row,
                "items": list_masuk
            })
    # Get pengiriman with item_masuk id
    elif type == '1':
        list_masuk = []
        my_object = item_masuk.objects.get(id=my_id)
        my_pengiriman = my_object.parent.pengiriman
        my_po = my_pengiriman.purchase_order

        for i in my_pengiriman.record_masuk.all():
            for j in i.item_dalam_record_masuk.all():
                list_masuk.append({
                    "nama": str(j.item_parent),
                    "gudang": j.gudang.nama,
                    "jumlah": j.item.jumlah,
                    "diterima": j.jumlah
                })

        list_pengiriman.append({
            "record": my_pengiriman,
            "items": list_masuk
        })
    # Get pengiriman with pengiriman id
    elif type == '2':
        list_masuk = []
        my_pengiriman = pengiriman.objects.get(id=my_id)
        my_po = my_pengiriman.purchase_order

        for i in my_pengiriman.record_masuk.all():
            for j in i.item_dalam_record_masuk.all():
                list_masuk.append({
                    "nama": str(j.item_parent),
                    "gudang": j.gudang.nama,
                    "jumlah": j.item.jumlah,
                    "diterima": j.jumlah
                })

        list_pengiriman.append({
            "record": my_pengiriman,
            "items": list_masuk
        })

    context = {
        "id": my_po.id,
        "type": type,
        "header": f"{my_po.penjual} | {my_po.ekspedisi} | {my_po.tanggal}",
        "list_pengiriman": list_pengiriman
    }

    modal_content = render_to_string('Purchasing/get_barang_masuk.html', context)
    return JsonResponse({'content': modal_content})


@login_required
def get_pengiriman(request):
    my_id = request.GET.get('id')

    my_po = purchase_order.objects.get(id=my_id)
    grand_total = 0
    list_pengiriman = []

    for row in my_po.pengiriman_dalam_PO.all():
        list_item_pengiriman = row.item_pengiriman.all().annotate(diterima=Coalesce(Sum('item_diterima__jumlah'), 0))
        my_total = list_item_pengiriman.aggregate(total=Sum(F('ongkos') * F('diterima')))['total']
        grand_total += my_total
        list_pengiriman.append({
            "record": row,
            "sampai": row.tanggal_sampai is not None,
            "items": list_item_pengiriman,
            "total_ongkos": my_total,
            "ada_keterangan": row.item_pengiriman.all().exclude(keterangan__exact='').exclude(
                keterangan__isnull=True).exists(),
        })

    context = {
        "id": my_po.id,
        "header": f"{my_po.penjual} | {my_po.ekspedisi} | {my_po.tanggal}",
        "list_pengiriman": list_pengiriman,
        "grand_total": grand_total
    }

    modal_content = render_to_string('Purchasing/get_pengiriman.html', context)
    return JsonResponse({'content': modal_content})


@login_required
def modify_po(request):
    my_id = request.GET.get('id')

    my_record = purchase_order.objects.get(id=my_id) if my_id else {
        "id": None, "penjual": "", "ekspedisi": "", "nomor_invoice": "",
        "tanggal": localdate(), "jatuh_tempo": localdate() + datetime.timedelta(days=30),
        "status_pembayaran": False, "status": False, "keterangan": ""
    }

    record_items = []
    if my_id != '':
        for row in my_record.item_PO.all():
            record_items.append({
                "id": row.item.id,
                "nama": row.item.nama,
                "label": str(row.item),
                "jumlah": row.jumlah,
                "harga": row.harga,
                "harga_total": row.jumlah * row.harga,
                "keterangan": "" if row.keterangan is None else row.keterangan
            })

    modal_content = render_to_string('Purchasing/modify_po.html', {
        "purchase_order": my_record,
        "item_po": json.dumps(record_items) if my_id != '' else None,
        "list_ekspedisi": purchase_order.objects.values('ekspedisi').distinct(),
        "list_penjual": purchase_order.objects.values('penjual').distinct()
    })
    return JsonResponse({'content': modal_content})


@login_required
def post_po(request):
    id_po = request.POST.get('id_po')
    penjual = request.POST.get('penjual').title()
    ekspedisi = request.POST.get('ekspedisi')
    nomor_invoice = request.POST.get('nomor_invoice')
    tanggal = request.POST.get('tanggal')
    jatuh_tempo = request.POST.get('jatuh_tempo')

    keterangan = request.POST.get('keterangan')
    keterangan = None if keterangan == "" else keterangan

    item_dalam_po = json.loads(request.POST.get('item_po'))
    target_item = None

    if id_po != "None":
        target_item = purchase_order.objects.get(id=id_po)
        updating = True
    else:
        updating = False

    if updating:
        target_item.penjual = penjual
        target_item.nomor_invoice = nomor_invoice
        target_item.ekspedisi = ekspedisi
        target_item.tanggal = tanggal
        target_item.jatuh_tempo = jatuh_tempo
        target_item.keterangan = keterangan
        target_item.save()
    else:
        target_item = purchase_order(penjual=penjual, nomor_invoice=nomor_invoice, ekspedisi=ekspedisi,
                                     tanggal=tanggal, jatuh_tempo=jatuh_tempo, keterangan=keterangan)
        target_item.save()

    if updating:
        target_item.item_PO.all().delete()

    for item in item_dalam_po:
        new_item = item_PO(purchase_order=target_item, item_id=item['id'], jumlah=item['jumlah'], harga=item['harga'],
                           keterangan=None if item['keterangan'] == "" else item['keterangan'])
        new_item.save()
        
    return JsonResponse({
        'message': f"Berhasil mengubah {target_item}" if updating else f"Berhasil menambahkan {target_item}"
    })


@login_required
def modify_pengiriman(request):
    my_id = request.GET.get('id')
    type = request.GET.get('type')

    my_record = None
    query = None
    ada_keterangan = False
    id_po = None

    # Type 0 = purchase order id (create new)
    if type == '0':
        my_record = {"id": None, "tanggal": localdate()}
        query = purchase_order.objects.get(id=my_id).item_PO.all()

templates/Purchasing/get_barang_masuk.html
{% load humanize %}
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable
            modal-fullscreen-md-down modal-xl">
    <div class="modal-content">
        <div class="modal-header heading_container">
            <div class="modal-title">
                <h3>Barang Masuk</h3>
                <h5>{{ header }}</h5>
            </div>

            <div class="button_container">
                {% if type != '0' %}
                    <button onclick="get_modal('get_barang_masuk', {{ id }}, 0)" class="btn btn-dark"><i class="fa-solid fa-arrows-up-down"></i>&ensp;Semua</button>
                {% endif %}
                <button onclick="get_modal('get_po', {{ id }})" class="btn btn-light"><i class="fa-solid fa-share flip"></i>&ensp;Ke PO</button>
            </div>
        </div>
        <div class="modal-body">
            <div class="row p-2">
                <table class="table table-striped table-bordered border-dark table-hover w-100">
                {% if type != '0' %}
                    <p style="font-style: italic">* Tidak menampilkan semua. Click tombol diatas untuk mengubah.</p>
                {% endif %}
                    <thead class="table-dark">
                        <tr>
                            <th colspan="3" class="action_cell">Pengiriman</th>
                            <th colspan="3" class="action_cell">Jumlah</th>
                        </tr>
                        <tr>
                            <th colspan="2">Berangkat <i class="fa-solid fa-arrow-right"></i> Sampai</th>
                            <th>Barang</th>
                            <th>Gudang</th>
                            <th class="action_cell">Nota</th>
                            <th class="action_cell">Masuk</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for i in list_pengiriman %}
                        <tr>
                            <td colspan="2" class="fw-bold">{{ i.record.tanggal }}
                                <i class="fa-solid fa-arrow-right"></i>
                                {% if i.record.tanggal_sampai %}{{ i.record.tanggal_sampai }}{% else %}Belum Sampai{% endif %}
                            </td>
                            <td colspan="4"></td>
                        </tr>
                        {% for j in i.items %}
                            <tr>
                                <td colspan="2"></td>
                                <td>{{ j.nama }}</td>
                                <td>{{ j.gudang }}</td>
                                <td class="num">{{ j.jumlah|intcomma }}</td>
                                <td class="num">{{ j.diterima|intcomma }}</td>
                            </tr>
                        {% endfor %}
                    {% empty %}
                        <tr class="action_cell"><td colspan="6">Tidak ada barang.</td></tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Tutup</button>
        </div>
    </div>
</div>

templates/Purchasing/riwayat_barang_masuk.html
{% load humanize %}
<div class="heading_container">
    <h3>{{ header }}</h3>
</div>
<hr>
<table class="table table-striped table-bordered border-dark table-hover w-100 dt_table">
        <thead class="table-dark">
            <th>No</th>
            <th>Pengiriman</th>
            <th>Tanggal<text class="min"> & Waktu</text></th>
            <th class="min">Admin</th>
            <th class="action_cell">Action</th>
        </thead>
        <tbody>
            {%  for record in riwayat %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ record.pengiriman }}</td>
                    <td>{{ record.tanggal }}<text class="min">, {{ record.waktu }}</text></td>
                    <td class="min">{{ record.admin.username }}</td>
                    <td class="action_cell">
                        <button onclick="get_modal('get_barang_masuk', {{ record.pengiriman_id }}, 2)" class="btn btn-primary btn-sm"><i class="fa-solid fa-magnifying-glass"></i></button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
</table>

templates/Purchasing/terima_pengiriman.html
{% load humanize %}
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-fullscreen">
    <div class="modal-content">
        <div class="modal-header heading_container">
            <figure class="figure">
                <h3 class="modal-title">
                    Terima pengiriman {{ pengiriman }}
                </h3>
                <h5 style="color: var(--primary-color)">
                    PO: {{ pengiriman.purchase_order.penjual }} |
                    {{ pengiriman.purchase_order.ekspedisi }},
                    No. Inv: {{ pengiriman.purchase_order.nomor_invoice }}</h5>
                <figcaption class="figure-caption mt-2" style="color: var(--light-primary-color)">{{ pengiriman.keterangan|default_if_none:"" }}</figcaption>
            </figure>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-12 col-lg-8 mb-2">
                    <div class="heading_container input_heading success">
                        <h5>Informasi Pengiriman</h5>
                        <button tabindex="5" form="barang_masuk_form" type="submit" class="btn btn-success">Simpan</button>
                    </div>
                    <form id="barang_masuk_form" class="input_form" onsubmit="post_barang_masuk(event)">
                        <input type="hidden" id="id_pengiriman" value="{{ pengiriman.id }}">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-4 col-xs-12 mb-2">
                                    <label>Tanggal Pengiriman</label>
                                    <input tabindex="1" type="date" class="form-control" value="{{ pengiriman.tanggal|date:'Y-m-d' }}" disabled>
                                </div>
                                <div class="col-md-4 col-xs-12 mb-2">
                                    <label>Tanggal Sampai</label>
                                    <input tabindex="2" type="date" class="form-control" id="tanggal_sampai"
                                        value="{% now 'Y-m-d' %}" required>
                                </div>
                                <div class="col-md-4 col-xs-12 mb-2">
                                    <label>Jam Sampai</label>
                                    <input tabindex="3" type="time" class="form-control" id="jam_sampai"
                                        value="{% now 'H:i' %}" required>
                                </div>
                            </div>
                        </div>
                    </form>

                    <br>

                    <h5>Barang dalam Pengiriman</h5>
                    <table class="table table-striped table-bordered border-dark table-hover w-100">
                        <thead class="table-dark">
                            <th>No</th>
                            <th>Barang</th>
                            <th>Gudang</th>
                            <th>Jumlah</th>
                            <th>Diterima</th>
                            <th>Expired</th>
                            <th>Keterangan</th>
                            <th class="action_cell">Action</th>
                        </thead>
                        <tbody>
                            {% for item in item_pengiriman %}
                            <tr id="form-{{ item.id }}">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ item.item_PO.item }}</td>
                                <td class="input_cell">
                                    <select class="form-control form-select" id="gudang">
                                        <option value=""></option>
                                        {% for gudang in list_gudang %}
                                            <option value="{{ gudang.id }}">{{ gudang.nama }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                                <td class="num">{{ item.jumlah|intcomma }}</td>
                                <td class="input_cell">
                                    <input id="jumlah_terima" class="form-control" type="number" value="{{ item.jumlah }}">
                                </td>
                                <td class="input_cell">
                                    <input id="expired" class="form-control" type="date">
                                </td>
                                <td class="input_cell">
                                    <textarea id="keterangan" class="form-control " rows="1" maxlength="200"></textarea>
                                </td>
                                <td class="action_cell">
                                    <button onclick="tambahkan_barang({{ item.id }}, {{ item.item_PO.item.id }})" type="button" class="btn btn-success btn-sm"><i class="fa-solid fa-right-to-bracket"></i></button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="col-md-12 col-lg-4 mt-5 mt-lg-0">
                    <h5>Barang Masuk</h5>
                    <table id="nota" class="table table-striped table-bordered border-dark table-hover w-100">
                        <thead class="table-dark">
                            <th>Barang</th>
                            <th>Gudang</th>
                            <th>Jumlah</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            <tr><td style="text-align: center" colspan="5">Belum ada barang masuk.</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Tutup</button>
            <button tabindex="4" form="barang_masuk_form" type="submit" class="btn btn-success">Simpan</button>
        </div>
    </div>
</div>

<script>
    $(function () {
        item_masuk = []

        map_gudang = {
        {% for gudang in list_gudang %}
            {{ gudang.id }}:'{{ gudang.nama }}',
        {% endfor %}
        }

        map_barang = {
        {% for item in item_pengiriman %}
            {{ item.id }}:['{{ item.item_PO.item }}', {{ item.jumlah }}],
        {% endfor %}
        }
    })

    modal.one('hidden.bs.modal', function () {
        if (item_masuk.length > 0){
            if(!confirm("Simpan data?")){
                item_masuk =[]
            }
        }
    })

    function validate_input(id, id_parent, jumlah, gudang_id) {
        if (gudang_id==="" || isNaN(jumlah)) {
            alert("Data barang tidak valid. Tolong diperiksa lagi.")
            return false
        }

        const sum_jumlah = item_masuk.reduce(function (sum, current) {
            if (current.item_parent_id === id_parent) {
                return sum + current.jumlah
            } else {
                return sum;
            }
        }, 0);

        if (jumlah + sum_jumlah > map_barang[id][1]) {
            alert("Jumlah keluar melebihi jumlah transaksi.")
            return false
        }

        return true
    }

    function tambahkan_barang(id, id_parent) {
        const parent = $(`#form-${id}`)
        let values = []

        parent.find('td.input_cell .form-control').each(function() {
            values.push($(this).val())
        })

        const keterangan = values.pop();
        const expired = values.pop();
        const jumlah = parseInt(values.pop());
        const gudang_id = values.pop()

        if (!validate_input(id, id_parent, jumlah, gudang_id)) {return}

        item_masuk.push({
            keterangan:keterangan,
            expired:expired,
            jumlah_terima:jumlah,
            gudang_id:gudang_id,
            item_parent_id:id_parent,
            item_id:id
        })

        parent.find('td.input_cell .form-control').each(function() {
            if ($(this).attr('type') === 'number') {
                $(this).val(0)
            } else {
                $(this).val('')
            }
        })
        parent.find('td.input_cell .form-control:first').focus()
        reload_table()
    }

    function hapus_barang(index) {
        item_masuk.splice(index, 1)
        reload_table()
    }

    function reload_table() {
        $('#nota tbody').empty();
        if (item_masuk.length == 0) {
            $('#nota > tbody:last-child').append('<tr><td class="action_cell" colspan="5">Belum ada barang masuk.</td></tr>'); return;
        }

        for (let i = 0; i < item_masuk.length; i++) {
            item = item_masuk[i]
            $('#nota > tbody:last-child').append(`
            <tr class="${(i%2==0)? 'even' : 'odd'}">

                <td>${map_barang[item.item_id][0]}</td>
                <td>${map_gudang[item.gudang_id]}</td>
                <td class="num">${item.jumlah_terima.toLocaleString()}</td>
                <td class="action_cell">
                    <button onclick="hapus_barang(${i})" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i></button>
                    ${(item.keterangan == "")? '' :
                    `
                    <button class="btn btn-primary btn-sm" data-bs-container="body" data-bs-toggle="popover"
                    data-bs-placement="bottom" title="Keterangan" data-bs-content="${item.keterangan}">
                    <i class="fa-solid fa-magnifying-glass"></i></button>
                    `}
                </td>
            </tr>`);
        }
        init_popover(modal)
    }

    function post_barang_masuk() {
        event.preventDefault();

        const id_pengiriman = $('#id_pengiriman').val();
        const tanggal_sampai = $('#tanggal_sampai').val();
        const jam_sampai = $('#jam_sampai').val();

        if (!confirm("Simpan catatan barang masuk?")) {return;}
        $.ajax({
            type: "POST",
            url: "{% url 'Purchasing:post_barang_masuk' %}",
            headers: {'X-CSRFToken': csrf_token},
            data: {
                id_pengiriman:id_pengiriman, tanggal_sampai:tanggal_sampai,
                jam_sampai:jam_sampai, item_masuk:JSON.stringify(item_masuk)
            },
            success: function (response) {
                alert(response.message)
                modal.modal('hide')
            },
            complete: function () {
                item_masuk = []
                get_page(current_page, true)
            }
        });
        return false;
    }
</script>